(function () {
 'use strict';
 var $=function(id){return document.getElementById(id);};
 var names=['You','Juniper','Luna','Moss'];
 var audio=new HearthAudio({master:.65,music:.28,ambience:.28});
 try{$('musicTrack').value=localStorage.getItem('hearthside-track')||'auto';}catch(e){}audio.setTrack($('musicTrack').value||'auto');
 $('musicTrack').addEventListener('change',function(){audio.setTrack(this.value);try{localStorage.setItem('hearthside-track',this.value);}catch(e){}});
 var teaReady=0;$('teaButton').addEventListener('click',function(){if(paused()||performance.now()<teaReady)return;teaReady=performance.now()+1000;audio.init();var sip=Math.random()<.5;audio.play(sip?'teaSip':'teaStir',{volume:.7,pan:.4});this.classList.remove('sipping','stirring');void this.offsetWidth;this.classList.add(sip?'sipping':'stirring');});
 audio.prepare(); // Open the silent device before the table's first interaction.
 var table=new Poker.Table({names:names}),started=false,busy=false,version=0,eventIndex=0;
 var visibleSeats=table.players.map(function(p){return {stack:p.stack,bet:0,folded:false,allIn:false,lastAction:''};});
 var companions=new HearthCompanions({onChange:renderSpeech});
 var computation=new HearthComputation(),guidePending={},guideErrors={};
 var ambience=new HearthAmbience($('stage'));
 var cat=new HearthCatDirector({onFrame:renderCat});
 var previousCatAction=null;
 function renderCat(frame,state){if(state.action==='spin'&&previousCatAction!=='spin'&&started)audio.play('catSpin',{volume:.35});previousCatAction=state.action;var el=$('windowCat');el.style.backgroundPosition=((frame%4)*100/3)+'% '+(frame>=4?100:0)+'%';el.dataset.action=state.action;el.dataset.frame=frame;el.setAttribute('aria-label','A ginger cat '+({sleep:'sleeping on the window cushion',stretch:'stretching',groom:'licking its paw',watch:'looking out the window',spin:'doing a rare spinning dance'}[state.action]||'resting'));}
 renderCat(cat.getState().frame,cat.getState());
 var visibleBoard=[],visiblePot=0,visibleStreet='idle',revealed=false,guideTab='possibilities',guideCache={},raiseOpen=false,lastFocus=null;
 var record={wins:0,losses:0,net:0,lastHand:0},handStartStack=500;
 var selectedCategory=null,restore=null,activeSeat=null,joining=false,pace="normal",checkpointData=null,saveFailed=false;
 var suit={s:'♠',h:'♥',d:'♦',c:'♣'},rank={11:'J',12:'Q',13:'K',14:'A'};
 var descriptions=['Your highest cards, when no stronger pattern is made.','Two cards of the same rank.','Two different pairs of matching ranks.','Three cards of the same rank.','Five consecutive ranks. An ace can be low or high.','Five cards of the same suit, in any order.','Three of one rank, plus a pair of another.','Four cards of the same rank.','Five consecutive ranks, all in the same suit.'];
 var examples=[['As','Jh','9c','6d','3s'],['Kh','Ks','9c','6d','3s'],['Kh','Ks','9c','9d','3s'],['7h','7s','7c','Kd','3s'],['9h','8s','7c','6d','5s'],['Ah','Jh','8h','6h','3h'],['Qh','Qs','Qc','8d','8s'],['5h','5s','5c','5d','As'],['9h','8h','7h','6h','5h']];
 function resize(){var scale=Math.min(innerWidth/1440,innerHeight/900);$('stage').style.transform='translate(-50%,-50%) scale('+scale+')';}addEventListener('resize',resize);resize();
 function safeStore(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch(e){}}
 try{restore=JSON.parse(localStorage.getItem('hearthside-session')||'null');if(restore&&restore.version===2){try{HearthSession.unpack(restore);}catch(err){restore=null;console.warn('Saved hand unavailable: '+err.message);}}var prefs=JSON.parse(localStorage.getItem('hearthside-settings')||'null');if(prefs){pace=["relaxed","normal","brisk"].includes(prefs.pace)?prefs.pace:"normal";audio.setMaster(prefs.master);audio.setMusic(prefs.music);audio.setAmbience(prefs.ambience);audio.setMuted(prefs.muted);$('reducedMotion').checked=!!prefs.gentle;$('stage').classList.toggle('gentle',!!prefs.gentle);}}catch(e){}
 function saveSettings(){var p=audio.getSettings();p.gentle=$('reducedMotion').checked;p.pace=pace;safeStore('hearthside-settings',p);}
 function card(c,opts){opts=opts||{};var el=document.createElement('div');el.className='card'+(!c?' back':(c.suit==='h'||c.suit==='d'?' red':''))+(opts.best?' best':'')+(opts.enter?' enter':'');if(c){var r=rank[c.rank]||c.rank,s=suit[c.suit];el.setAttribute('aria-label',r+' of '+({s:'spades',h:'hearts',d:'diamonds',c:'clubs'}[c.suit]));el.dataset.card=Poker.cardKey(c);el.innerHTML='<div class="corner">'+r+'<span>'+s+'</span></div><div class="center-suit">'+s+'</div><div class="corner bottom">'+r+'<span>'+s+'</span></div>';}else{el.innerHTML='<span>✦</span>';el.setAttribute('aria-label','Face-down card');}return el;}
 function emptyCard(i){var e=document.createElement('div');e.className='card empty';e.textContent=['✧','✧','✧','·','·'][i];e.title=['Flop','Flop','Flop','Turn','River'][i]+' · not dealt yet';return e;}
 function replaceCards(el,cards,opts){var sig=cards.map(function(c){return c?Poker.cardKey(c):'?';}).join(',')+'|'+(opts&&opts.best||[]).join(',');if(el.dataset.sig===sig)return;var old=(el.dataset.sig||'').split('|')[0].split(',');el.dataset.sig=sig;el.innerHTML='';cards.forEach(function(c,i){el.appendChild(card(c,{best:c&&opts&&opts.best&&opts.best.indexOf(Poker.cardKey(c))>=0,enter:opts&&opts.animate&&old[i]!==(c?Poker.cardKey(c):'?')}));});}
 function current(){return Poker.evaluate(table.players[0].hole.concat(visibleBoard));}
 function paused(){return !$('journal').classList.contains('hidden')||['settings','rules','confirmReset','recap'].some(function(id){return !$(id).classList.contains('hidden');});}
 function syncScenePause(){var context=companionContext();$('stage').classList.toggle('scene-paused',context.paused||context.hidden);ambience.setPaused(context.paused);cat.tick(0,{paused:context.paused,hidden:context.hidden,gentle:$('reducedMotion').checked});}
 function wait(ms,t){return new Promise(function(resolve){var left=ms,last=Date.now();function tick(){if(t!==version){resolve(false);return;}var now=Date.now();if(!paused()&&!document.hidden)left-=(now-last)/HearthSession.paceFactor(pace);last=now;if(left<=0){resolve(true);return;}setTimeout(tick,40);}tick();});}
 function sound(name,id){audio.play(name,{pan:id>0?Number($('seat'+id).dataset.pan):0});}
 function renderSpeech(state){for(var id=1;id<table.players.length;id++){var bubble=$('speech'+id),active=state.speakerId===id;bubble.textContent=active?state.line:'';bubble.classList.toggle('show',active&&state.visible);bubble.setAttribute('aria-hidden',active&&state.visible?'false':'true');bubble.setAttribute('aria-live','polite');}}
 function companionContext(){return {paused:paused(),hidden:document.hidden};}
 function applyPublicEvent(e){
  if(e.type==='hand-start')companions.handle({type:'hand-start',participantIds:visibleSeats.map(function(p,id){return p.folded?null:id;}).filter(function(id){return id!==null;})},companionContext());
  if(e.type==='blind'||e.type==='action'){var p=visibleSeats[e.playerId];p.stack=Math.max(0,p.stack-(e.amount||0));p.bet+=e.amount||0;if(e.action==='fold')p.folded=true;p.allIn=!p.folded&&p.stack===0;p.lastAction=e.text||(e.label+' '+e.amount);if(e.type==='action')companions.handle({type:'action',playerId:e.playerId,action:e.action,allIn:p.allIn},companionContext());}
  if(e.type==='street')visibleSeats.forEach(function(p){p.bet=0;if(!p.folded&&!p.allIn)p.lastAction='';});
  if(e.type==='result'){visibleSeats.forEach(function(p,id){p.stack=table.players[id].stack;p.bet=0;});companions.handle({type:'result',winnerIds:e.result.winners.filter(function(w){return w.wonAmount>0;}).map(function(w){return w.id;})},companionContext());}
 }
 function burst(x,y,count){if($('reducedMotion').checked)return;for(var i=0;i<count;i++){var p=document.createElement('span');p.className='particle';p.textContent=i%3?'✦':'◉';p.style.left=x+'px';p.style.top=y+'px';p.style.setProperty('--dx',(Math.random()-.5)*260+'px');p.style.setProperty('--dy',(-40-Math.random()*170)+'px');p.style.animationDelay=(i*.025)+'s';$('particles').appendChild(p);setTimeout(function(node){return function(){node.remove();};}(p),2000);}}
 function configureSeats(){HearthRoster.mount(table.players);companions.roster=table.players.slice(1).map(function(p){return HearthRoster.all.findIndex(function(c){return c.name===p.name;})+1;});}
 function setupChoices(){HearthRoster.setup(names.slice(1));}
 function seatPoint(id){var el=$('seat'+id);return el?[Number(el.dataset.chipX),Number(el.dataset.chipY)]:[720,780];}
 function chipFlight(id){if($('reducedMotion').checked)return;var from=id===0?[720,780]:seatPoint(id);for(var i=0;i<4;i++){var p=document.createElement('span');p.className='particle';p.textContent='◉';p.style.left=from[0]+i*3+'px';p.style.top=from[1]+'px';p.style.setProperty('--dx',(755-from[0])+'px');p.style.setProperty('--dy',(483-from[1])+'px');p.style.animationDuration=(.65*HearthSession.paceFactor(pace))+'s';p.style.animationDelay=i*.045+'s';$('particles').appendChild(p);setTimeout(function(n){return function(){n.remove();};}(p),950);}}
 function render(){var snap=table.snapshot(),ev=current(),keys=visibleBoard.length>=3?ev.bestCards.map(Poker.cardKey):[];
  $('handNo').textContent='HAND '+String(table.handNumber||1).padStart(2,'0');$('potValue').textContent=visiblePot.toLocaleString();
  $('streetRibbon').textContent=visibleStreet==='idle'?'':visibleStreet.toUpperCase();
  var chips='';for(var c=0;c<Math.min(11,Math.ceil(visiblePot/15));c++)chips+='<i class="chip '+(c%3===1?'green':c%3===2?'purple':'')+'" style="left:'+((c%3)*15)+'px;bottom:'+Math.floor(c/3)*4+'px"></i>';$('chipPile').innerHTML=chips;
  for(var i=1;i<table.players.length;i++){var p=snap.players[i],v=visibleSeats[i],seat=$('seat'+i),mood=started?(v.folded?'folded':v.allIn?'allin':'playing'):'playing';seat.querySelector('.stack').textContent=v.stack.toLocaleString();seat.querySelector('.status').textContent=!started?'Ready':(activeSeat===i&&!revealed?'Their turn':v.lastAction||(v.folded?'Resting':''));seat.querySelector('.dealer-token').style.display=started&&snap.dealer===i?'block':'none';seat.classList.toggle('active',started&&activeSeat===i&&!revealed);seat.querySelector('.nameplate').setAttribute('aria-current',activeSeat===i?'true':'false');HearthPresentation.renderChips(seat.querySelector('.npc-chips'),v.stack,names[i]);seat.classList.toggle('folded',started&&v.folded);seat.dataset.mood=mood;var sprite=seat.querySelector('.sprite');sprite.setAttribute('role','img');sprite.setAttribute('aria-label',names[i]+', '+(mood==='allin'?'all in':mood==='folded'?'sitting this hand out':'playing'));replaceCards(seat.querySelector('.opponent-cards'),started?p.hole.map(function(c){return revealed?c:null;}):[null,null],{animate:true});}
  var boardSig=visibleBoard.map(Poker.cardKey).join(',')+'|'+keys.join(',');if($('board').dataset.sig!==boardSig){var oldKeys=($('board').dataset.sig||'').split('|')[0];$('board').dataset.sig=boardSig;$('board').innerHTML='';for(var b=0;b<5;b++)$('board').appendChild(visibleBoard[b]?card(visibleBoard[b],{best:keys.indexOf(Poker.cardKey(visibleBoard[b]))>=0,enter:oldKeys.indexOf(Poker.cardKey(visibleBoard[b]))<0}):emptyCard(b));}
  replaceCards($('holeCards'),started?table.players[0].hole:[null,null],{animate:true,best:keys});
  $('humanStack').textContent=visibleSeats[0].stack.toLocaleString();
  $('sessionRecord').textContent=record.wins+'W · '+record.losses+'L · '+(record.net>=0?'+':'')+record.net+' chips';
  for(var pos=0;pos<table.players.length;pos++){var host=pos===0?$('humanPositions'):$('seat'+pos).querySelector('.position-markers');if(!host){host=document.createElement('div');host.className='position-markers';$('seat'+pos).querySelector('.nameplate').appendChild(host);}var positionSig=started?table.handNumber+'|'+table.dealer+'|'+table.events.slice(0,eventIndex+1).filter(function(e){return e.type==='blind'&&e.playerId===pos;}).map(function(e){return e.label;}).join(','):'idle';if(host.dataset.sig===positionSig)continue;host.dataset.sig=positionSig;host.innerHTML='';if(started){if(pos===table.dealer){var d=document.createElement('span');d.textContent='D';d.title='Dealer';host.appendChild(d);}table.events.slice(0,eventIndex+1).filter(function(e){return e.type==='blind'&&e.playerId===pos;}).forEach(function(e){var m=document.createElement('span');m.textContent=e.label==='Small blind'?'SB':'BB';m.title=e.label+' · '+e.amount+' chips';m.className='blind-marker';host.appendChild(m);});}}
 $('humanBet').textContent=started?(visibleSeats[0].folded?'Sitting this hand out.':visibleSeats[0].allIn?'All in.':visibleSeats[0].bet?'In this round: '+visibleSeats[0].bet+' chips':''):'';
  $('humanDealer').style.display=started&&table.dealer===0?'block':'none';$('currentHand').textContent=started?(visibleBoard.length<3?(ev.category===1?'Pocket '+(rank[table.players[0].hole[0].rank]||table.players[0].hole[0].rank)+'s':(rank[ev.tiebreak[0]]||ev.tiebreak[0])+' high'):ev.name):'No cards';
  var boardPair=visibleBoard.filter(function(c){return c.rank===ev.tiebreak[0];}).length>=2;
  $('handSource').textContent=started&&visibleBoard.length>=3&&ev.category===1?(boardPair?'Pair on the board · shared by everyone':'Pair uses your cards'):'';
  $('peekButton').title='Best five cards from your hand and the shared board';
  renderActions();if(!$('journal').classList.contains('hidden'))renderJournal();
 }
 function setMessage(text,win){$('tableMessage').textContent=text;$('tableMessage').classList.toggle('winner-banner',!!win);}
 function renderActions(){var btns=$('actionButtons'),oldRaise=$('raisePanel');if(oldRaise)oldRaise.remove();raiseOpen=false;
  if(joining){$('turnText').textContent='TAKING YOUR SEAT';$('turnHint').textContent='';btns.innerHTML='<button disabled class="primary">Settling in…</button>';return;}
  if(!started){$('turnText').textContent='YOUR CHAIR IS WAITING';$('turnHint').textContent=restore?(restore.version===2?'Your unfinished hand is saved.':'Your last finished table is saved.'):'A friendly table. All make-believe chips.';btns.innerHTML='<button id="startButton" class="primary">'+(restore?'Return to the table':'Take a seat')+' <span>↗</span></button>';return;}
  if(busy){$('turnText').textContent=activeSeat>0?names[activeSeat].toUpperCase()+'’S TURN':'DEALING';$('turnHint').textContent='';btns.innerHTML='<button disabled class="subtle-button">Fold</button><button disabled>Check / call</button><button disabled class="raise-button">Raise</button>';return;}
  if(revealed){var busted=table.players[0].stack===0,won=!busted&&table.gameOver,finished=busted||won;$('turnText').textContent=finished?'TABLE FINISHED':'HAND COMPLETE';$('turnHint').textContent=won?'You won the table.':busted?'You are out of chips, but the table can continue.':'';btns.innerHTML='<button id="recapButton">Review hand</button>'+(busted?'<button id="freshTable" class="subtle-button">Fresh table</button><button id="nextHand" class="primary">Rebuy '+table.startingStack+' chips <span>↗</span></button>':'<button id="nextHand" class="primary">'+(finished?'A fresh table':'Deal next hand')+' <span>↗</span></button>');return;}
  if(table.actor!==0){$('turnText').textContent='WAITING';$('turnHint').textContent='Your companions are finishing the hand.';btns.innerHTML='<button disabled>Cards in motion…</button>';return;}
  var l=table.legalActions();$('turnText').textContent='YOUR TURN';$('turnHint').textContent=l.check?'':l.call+' chips to call';
  btns.innerHTML='<button data-action="fold" class="subtle-button">Fold <small>F</small></button><button data-action="'+(l.check?'check':'call')+'" class="primary">'+HearthPresentation.callLabel(l,table.players[0].stack)+' <small>C</small></button><button id="raiseToggle" class="raise-button" '+(!l.canRaise?'disabled':'')+'>'+(table.currentBet?'Raise':'Bet')+' <span>⌃</span></button>';
 }
 async function drive(t){busy=true;activeSeat=null;render();while(t===version){while(eventIndex<table.events.length){if(!await wait(30,t))return;var e=table.events[eventIndex];applyPublicEvent(e);if(e.type==='hand-start'){sound('shuffle');visibleStreet='preflop';visibleBoard=[];revealed=false;visiblePot=0;render();checkpoint(eventIndex+1);for(var d=0;d<table.players.filter(function(p){return p.hole.length;}).length*2;d++){sound('deal',d%table.players.length);if(!await wait(75,t))return;}setMessage('');}
    if(e.type==='blind'||e.type==='action'){visiblePot+=e.amount||0;if(e.type==='action'){sound(e.action==='call'?'chips':e.action==='allin'?'raise':e.action,e.playerId);setMessage(names[e.playerId]+' · '+e.text);}else sound('chips',e.playerId);if(e.amount)chipFlight(e.playerId);if(e.playerId>0){var badge=$('seat'+e.playerId).querySelector('.bet-feedback');if(!badge){badge=document.createElement('div');badge.className='bet-feedback';badge.setAttribute('role','status');$('seat'+e.playerId).appendChild(badge);}badge.textContent=e.text||(e.label+' '+e.amount);badge.classList.remove('show');void badge.offsetWidth;badge.style.setProperty('--feedback-time',(2.4*HearthSession.paceFactor(pace))+'s');badge.classList.add('show');}render();checkpoint(eventIndex+1);if(!await wait(e.type==='blind'?550:350,t))return;}
    if(e.type==='street'){visibleStreet=e.street;setMessage({flop:'',turn:'',river:''}[e.street]);for(var k=Math.max(0,visibleBoard.length-(e.board.length-e.cards.length));k<e.cards.length;k++){visibleBoard.push(e.cards[k]);sound('flip');render();checkpoint();if(!await wait(320,t))return;}if(!await wait(220,t))return;}
    if(e.type==='result'){if(record.lastHand!==table.handNumber){var delta=table.players[0].stack-handStartStack;record.wins+=delta>0?1:0;record.losses+=delta<0?1:0;record.net+=delta;record.lastHand=table.handNumber;}revealed=true;visibleStreet='showdown';visiblePot=e.result.totalPot;var wins=e.result.winners.filter(function(w){return w.wonAmount>0;});setMessage(HearthPresentation.resultLabel(e.result,names),true);var humanWin=wins.some(function(w){return w.id===0;});sound(humanWin?'win':'lose');burst(humanWin?720:seatPoint(wins[0]?wins[0].id:0)[0],humanWin?714:425,humanWin?22:9);$('potValue').classList.add('burst');setTimeout(function(){$('potValue').classList.remove('burst');},500);render();checkpoint(eventIndex+1);if(!await wait(500,t))return;}
    eventIndex++;checkpoint();
   }
   if(table.result||table.actor===0||table.actor===null)break;
   var ai=table.actor;activeSeat=ai;render();$('seat'+ai).classList.add('thinking');if(!await wait(850+Math.random()*550,t))return;$('seat'+ai).classList.remove('thinking');activeSeat=null;try{table.stepAI();checkpoint();}catch(err){console.error(err);setMessage('The table needs a fresh start. '+err.message);break;}
  }if(t!==version)return;busy=false;activeSeat=table.result?null:table.actor;render();checkpoint();if(table.actor===0&&!table.result)sound('turn');if(table.result){renderRecap();openModal('recap');}
 }
 async function start(){if(joining||started)return;audio.init();if(restore&&restore.version===2){var saved=HearthSession.unpack(restore);table=saved.table;table.players.forEach(function(p){if(p.name==='Luma')p.name='Luna';});names=table.players.map(function(p){return p.name;});configureSeats();window.hearth.table=table;var ui=saved.ui;record=ui.record||{wins:0,losses:0,net:0,lastHand:table.result?table.handNumber:0};handStartStack=ui.handStartStack===undefined?table.players[0].stack+table.players[0].totalBet:ui.handStartStack;visibleSeats=ui.visibleSeats;visibleBoard=ui.visibleBoard;visiblePot=ui.visiblePot;visibleStreet=ui.visibleStreet;revealed=ui.revealed;eventIndex=ui.eventIndex;setMessage(ui.message||'Hand resumed.');restore=null;started=true;joining=false;$('stage').classList.add('seated');checkpoint();drive(++version);return;}joining=true;busy=true;activeSeat=null;$('stage').classList.add('joining','seated');companions.clear();renderActions();audio.play('fold',{volume:.35,pitch:.6});var token=++version;if(!await wait($('reducedMotion').checked?40:1250,token))return;$('stage').classList.remove('joining');joining=false;busy=false;started=true;newHand();}
 function newHand(){if(busy)return;handStartStack=table.players[0].stack;version++;companions.clear();visibleSeats=table.players.map(function(p){return {stack:p.stack,bet:0,folded:p.stack===0,allIn:false,lastAction:p.stack===0?'Resting':''};});visibleBoard=[];visiblePot=0;visibleStreet='preflop';revealed=false;guideCache={};guidePending={};guideErrors={};computation.invalidate();selectedCategory=null;$('board').dataset.sig='';$('holeCards').dataset.sig='';table.events=[];eventIndex=0;document.querySelectorAll(".bet-feedback").forEach(function(el){el.classList.remove("show");});if(!table.newHand()){reset();return;}checkpoint();drive(version);}
 function checkpoint(nextEventIndex){if(!started||joining)return;checkpointData=HearthSession.pack(table,{eventIndex:nextEventIndex===undefined?eventIndex:nextEventIndex,visibleSeats:visibleSeats,visibleBoard:visibleBoard,visiblePot:visiblePot,visibleStreet:visibleStreet,revealed:revealed,record:record,handStartStack:handStartStack,message:$('tableMessage').textContent});saveSession();}
 function saveSession(){if(!checkpointData)return;try{localStorage.setItem('hearthside-session',JSON.stringify(checkpointData));saveFailed=false;}catch(e){saveFailed=true;}if($('saveStatus'))$('saveStatus').textContent=saveFailed?'The hand could not be saved. Keep this window open to preserve it.':started?'Your hand is saved automatically.':'';}
 function renderRecap(){var busted=table.players[0].stack===0;$('recapNextHand').textContent=busted?'Rebuy '+table.startingStack+' chips ↗':(table.gameOver?'A fresh table ↗':'Deal next hand ↗');var target=$('recapContent');target.innerHTML='';target.scrollTop=0;HearthSession.recap(table.result,names).forEach(function(pot){var section=document.createElement('section');var heading=document.createElement('h3');heading.textContent=pot.title;section.appendChild(heading);pot.winners.forEach(function(w){var name=document.createElement('strong');name.textContent=w.name+(w.hand?' · '+w.hand:'')+' · '+w.amount+' chips';section.appendChild(name);var cards=document.createElement('div');cards.className='recap-cards';w.cards.forEach(function(c){cards.appendChild(card(c,{best:true}));});section.appendChild(cards);});var detail=document.createElement('p');detail.textContent=pot.text;section.appendChild(detail);target.appendChild(section);});}
 function quitGame(){saveSession();if(saveFailed)return;if(window.hearthDisplay)window.hearthDisplay.quit();}

 function rebuy(){if(busy||table.players[0].stack>0)return;table.players[0].stack=table.startingStack;newHand();}
 function reset(){record={wins:0,losses:0,net:0,lastHand:0};handStartStack=500;version++;companions.clear();busy=false;activeSeat=null;joining=false;$('stage').classList.remove('joining');$('stage').classList.add('seated');table=new Poker.Table({names:names});configureSeats();window.hearth.table=table;restore=null;checkpointData=null;safeStore('hearthside-session',null);closeAll();document.querySelectorAll('.thinking').forEach(function(e){e.classList.remove('thinking');});started=true;eventIndex=0;newHand();}
 function act(type,amount){if(!started||joining||busy||paused()||table.actor!==0||revealed)return;audio.init();try{table.act(0,type,amount);checkpoint();drive(version);}catch(err){setMessage(err.message);renderActions();}}
 function raisePanel(){if(raiseOpen){renderActions();return;}var l=table.legalActions();if(!l.canRaise)return;raiseOpen=true;var min=Math.min(l.minRaiseTo,l.maxRaiseTo),p=document.createElement('div');p.className='raise-controls';p.id='raisePanel';p.innerHTML='<label>'+(table.currentBet?'Raise to':'Bet')+' (total this round)<input id="raiseNumber" type="number" min="'+min+'" max="'+l.maxRaiseTo+'" step="1" value="'+min+'" aria-label="Raise total"></label><input id="raiseRange" type="range" min="'+min+'" max="'+l.maxRaiseTo+'" value="'+min+'" aria-label="Raise amount slider"><div class="raise-presets"><button data-raise="min">Minimum</button><button data-raise="half">½ pot</button><button data-raise="pot">Pot</button><button data-raise="all">All in</button><button id="raiseConfirm" class="primary">Confirm</button></div>';$('actions').appendChild(p);sound('click');}
 function analysisKey(){return table.players[0].hole.concat(visibleBoard).map(Poker.cardKey).join(',');}
 function getAnalysis(){var hole=table.players[0].hole,key=analysisKey();if(guideCache[key])return guideCache[key];if(!guidePending[key]&&!guideErrors[key]){var seed=1;key.split('').forEach(function(c){seed=(seed*31+c.charCodeAt(0))>>>0;});var token={version:version};guidePending[key]=token;computation.analyze(hole,visibleBoard,{samples:12000,seed:seed,key:key}).then(function(result){if(token.version!==version||guidePending[key]!==token)return;delete guidePending[key];guideCache[key]=result;if(analysisKey()===key&&!$('journal').classList.contains('hidden'))renderJournal();}).catch(function(err){if(token.version!==version||guidePending[key]!==token)return;delete guidePending[key];if(err&&err.name==='AbortError')return;guideErrors[key]=true;console.warn('Hand guide: '+(err&&err.message||'analysis unavailable'));if(analysisKey()===key&&!$('journal').classList.contains('hidden'))renderJournal();});}return null;}

 function cardExample(arr){return '<div class="row-cards">'+arr.map(function(c){var s=c.slice(-1);return '<i class="'+(s==='h'||s==='d'?'red':'')+'">'+c.slice(0,-1)+suit[s]+'</i>';}).join('')+'</div>';}
 function renderJournal(){var sum=$('journalSummary'),rows=$('journalRows');sum.innerHTML='';rows.innerHTML='';$('journalDetail').innerHTML='';
  if(guideTab==='rankings'){rows.innerHTML='<p class="summary-note" style="margin:0 0 12px">Strongest to simplest. Choose any row to learn more. The best five cards count; suits never break ties.</p><button class="guide-row" data-category="9"><span class="rank">01</span><span><strong>Royal flush</strong><small>The highest possible straight flush</small>'+cardExample(['Ah','Kh','Qh','Jh','10h'])+'</span><span class="chance">✦</span></button>';for(var c=8;c>=0;c--)rows.innerHTML+='<button class="guide-row" data-category="'+c+'"><span class="rank">'+String(10-c).padStart(2,'0')+'</span><span><strong>'+Poker.CATEGORY_NAMES[c]+'</strong><small>'+descriptions[c]+'</small>'+cardExample(examples[c])+'</span></button>';if(selectedCategory!==null)renderDetail(selectedCategory);return;}
  if(!started||table.players[0].hole.length!==2){sum.innerHTML='<div class="journal-summary"><h3>A little guide to possibility.</h3><p class="summary-note">Take a seat to see your cards here. As the community cards appear, this journal will show your current hand and the hands you could still make.</p></div>';rows.innerHTML='<p class="summary-note">You can browse all ten hand rankings in the tab above.</p>';return;}
  if(visibleBoard.length===1||visibleBoard.length===2){sum.innerHTML='<div class="journal-summary"><h3>The flop is arriving…</h3><div class="visible-cards"></div><p class="summary-note">Close the journal to let all three flop cards settle. Then we can explore the complete set of possibilities.</p></div>';var partial=sum.querySelector('.visible-cards');table.players[0].hole.concat(visibleBoard).forEach(function(c){partial.appendChild(card(c));});return;}
  var a=getAnalysis();if(!a){var loading=document.createElement('div');loading.className='journal-summary';loading.innerHTML='<span class="eyebrow">YOUR VISIBLE CARDS</span><h3>'+$('currentHand').textContent+'</h3><div class="visible-cards"></div>';var best=visibleBoard.length>=3?current().bestCards.map(Poker.cardKey):[];table.players[0].hole.concat(visibleBoard).forEach(function(c){loading.querySelector('.visible-cards').appendChild(card(c,{best:best.indexOf(Poker.cardKey(c))>=0}));});sum.appendChild(loading);rows.innerHTML='<p class="summary-note" role="status">'+(guideErrors[analysisKey()]?'Close and reopen the journal to try again.':'Looking at your possibilities…')+'</p>';return;}var wrap=document.createElement('div');wrap.className='journal-summary';wrap.innerHTML='<span class="eyebrow">'+(visibleBoard.length<3?'YOUR STARTING CARDS':'YOUR BEST VISIBLE HAND')+'</span><h3>'+$('currentHand').textContent+'</h3><div class="visible-cards"></div><p class="summary-note">'+(visibleBoard.length<3?'A five-card hand forms when the flop arrives.':a.current.bestCards.length+' gold-edged cards make your best current hand.')+'</p>';var vc=wrap.querySelector('.visible-cards');table.players[0].hole.forEach(function(c){vc.appendChild(card(c,{best:visibleBoard.length>=3&&a.bestCardKeys.indexOf(Poker.cardKey(c))>=0}));});if(visibleBoard.length){var div=document.createElement('span');div.className='visible-divider';vc.appendChild(div);visibleBoard.forEach(function(c){vc.appendChild(card(c,{best:a.bestCardKeys.indexOf(Poker.cardKey(c))>=0}));});}sum.appendChild(wrap);
  rows.innerHTML='<div class="eyebrow" style="margin:0 0 5px">'+(visibleBoard.length===5?'YOUR FINAL HAND':'BY THE RIVER')+'</div><p class="summary-note" style="margin:0 0 8px">'+a.sampleLabel+'. '+(!a.exact?'Rare hands may not appear in the sample. Choose a hand to see an example.':'')+'</p>';
  a.rows.slice().reverse().forEach(function(row,i){var pct=row.probability*100,label=pct===100?'100%':pct===0?(a.exact?'0%':'—'):pct<.1?'<0.1%':pct.toFixed(1)+'%';var note=visibleBoard.length<3?(row.current?'Your starting pattern':'Possible final hand'):row.current?'Your current category':row.outs.length?row.outs.length+' next cards make this category':row.possible===false?'Cannot finish in this category':'Possible final hand';if(!a.exact&&pct===0&&row.possible!==false)note='Rare · not sampled';if(row.possible===false){label='0%';note='Cannot finish in this category';}rows.innerHTML+='<button class="guide-row '+(row.current?'current ':'')+(row.possible===false?'unavailable':'')+'" data-category="'+row.category+'"><span class="rank">'+String(i+1).padStart(2,'0')+'</span><span><strong>'+(row.category===8?'Straight / royal flush':row.name)+'</strong><small>'+note+'</small></span><span class="chance">'+label+'</span><span class="bar" style="width:'+Math.max(0,pct*3.18)+'px"></span></button>';});if(selectedCategory!==null)renderDetail(selectedCategory);
 }
 function hypotheticalHTML(example){if(!example)return '<p>No example of this rare outcome appeared in the sample. It may still be possible.</p>';var futureKeys=example.futureBoard.map(Poker.cardKey);return '<p><b>One possible version of your hand</b><br>This is an illustration, not a prediction of the deck.</p><div class="example-hand">'+example.bestCards.map(function(c){var k=Poker.cardKey(c),isFuture=futureKeys.indexOf(k)>=0,label=isFuture?'POSSIBLE':example.usedHoleKeys.indexOf(k)>=0?'YOURS':'TABLE';return '<div class="example-slot '+(isFuture?'hypothetical':'')+'">'+card(c).outerHTML+'<small>'+label+'</small></div>';}).join('')+'</div>'+(example.futureBoard.length?'<p>Example future board: '+example.futureBoard.map(function(c){return (rank[c.rank]||c.rank)+suit[c.suit];}).join(' · ')+'. Dotted cards above have not been dealt.</p>':'');}
 function renderDetail(c){selectedCategory=c;var title=c===9?'Royal flush':Poker.CATEGORY_NAMES[c];var html='<div class="guide-detail"><b>'+title+'</b><br>'+(c===9?'Ten, jack, queen, king and ace in the same suit. This is the strongest straight flush.':descriptions[c])+cardExample(c===9?['Ah','Kh','Qh','Jh','10h']:examples[c]);if(guideTab==='possibilities'&&started){var a=getAnalysis(),row=a&&a.rows[c];if(row&&row.possible!==false)html+=hypotheticalHTML(row.example);if(row&&visibleBoard.length>=3&&visibleBoard.length<5){html+='<p>These unseen <b>next cards</b> immediately change your current hand to this stronger category. They are not guaranteed winning cards.</p>';if(row.outs.length)html+='<div class="out-cards">'+row.outs.map(function(k){var s=k.slice(-1),r=Number(k.slice(0,-1));return '<span class="out-card '+(s==='h'||s==='d'?'red':'')+'">'+(rank[r]||r)+suit[s]+'</span>';}).join('')+'</div>';else html+='<p>No single next card immediately upgrades you to this category. The final-hand percentage also includes two-card possibilities when two board cards remain.</p>';}else if(visibleBoard.length===5)html+='<p>All community cards are visible. Your final category is settled.</p>';else html+='<p>The percentages sample possible five-card boards. Specific next-card improvements become useful once the flop appears.</p>';}html+='</div>';$('journalDetail').innerHTML=html;}
 function openJournal(){audio.init();delete guideErrors[analysisKey()];lastFocus=document.activeElement;closeAll(false);$('journalBackdrop').classList.remove('hidden');$('journal').classList.remove('hidden');syncScenePause();renderJournal();sound('guideOpen');$('closeJournal').focus();}
 function closeAll(focus){var had=paused();$('journal').classList.add('hidden');['settings','rules','confirmReset','recap'].forEach(function(id){$(id).classList.add('hidden');});$('journalBackdrop').classList.add('hidden');syncScenePause();if(had)sound('guideClose');if(focus!==false&&lastFocus&&lastFocus.isConnected)lastFocus.focus();}
 function openModal(id){audio.init();lastFocus=document.activeElement;closeAll(false);$('journalBackdrop').classList.remove('hidden');$(id).classList.remove('hidden');syncScenePause();sound('guideOpen');var focus=$(id).querySelector('button,input,select');if(focus)focus.focus();}
 document.addEventListener('click',function(e){var b=e.target.closest('button');if(!b||b.disabled)return;var id=b.id;if(b.dataset.close){closeAll();return;}if(b.dataset.action){act(b.dataset.action);return;}if(b.dataset.tab){guideTab=b.dataset.tab;selectedCategory=null;document.querySelectorAll('.journal-tabs button').forEach(function(x){x.classList.toggle('selected',x===b);});sound('click');renderJournal();return;}if(b.dataset.category!==undefined){renderDetail(Number(b.dataset.category));sound('click');$('journalDetail').scrollIntoView({block:'nearest',behavior:$('reducedMotion').checked?'auto':'smooth'});return;}if(b.dataset.raise){var l=table.legalActions(),min=Math.min(l.minRaiseTo,l.maxRaiseTo),v=b.dataset.raise==='min'?min:b.dataset.raise==='all'?l.maxRaiseTo:table.currentBet+Math.round((table.pot+l.call)*(b.dataset.raise==='half'?.5:1));v=Math.max(min,Math.min(l.maxRaiseTo,v));$('raiseRange').value=$('raiseNumber').value=v;sound('chips');return;}
  if(id==='resumeGame')closeAll();else if(id==='settingsRules')openModal('rules');else if(id==='quitGame'||id==='windowQuit')quitGame();else if(id==='recapButton'){renderRecap();openModal('recap');}else if(id==='startButton')start();else if(id==='nextHand'||id==='recapNextHand'){if(busy||!revealed)return;closeAll(false);audio.init();if(table.players[0].stack===0)rebuy();else if(table.gameOver)reset();else newHand();}else if(id==='freshTable'){if(busy||!revealed)return;closeAll(false);audio.init();reset();}else if(id==='guideButton'||id==='peekButton')openJournal();else if(id==='closeJournal')closeAll();else if(id==='soundButton'){syncSettings();openModal('settings');}else if(id==='tableSetup'){setupChoices();openModal('confirmReset');}else if(id==='rulesButton')openModal('rules');else if(id==='newTableButton'){setupChoices();openModal('confirmReset');}else if(id==='resetConfirm'){var selected=HearthRoster.selected();if(selected.length!==Number($('tableSize').value)-1)return;names=['You'].concat(selected);reset();}else if(id==='raiseToggle')raisePanel();else if(id==='raiseConfirm'){var n=Number($('raiseNumber').value);act('raise',n);}else if(id==='muteButton'){audio.toggleMute();syncSettings();saveSettings();}else if(id==='testSound'){audio.init();audio.play('chips',{intensity:1});}
 });
 $('gamePace').addEventListener('change',function(){pace=this.value;$('stage').style.setProperty('--pace',HearthSession.paceFactor(pace));saveSettings();});
 $('journalBackdrop').addEventListener('click',function(){closeAll();});
 document.addEventListener('input',function(e){var id=e.target.id;if(id==='raiseRange')$('raiseNumber').value=e.target.value;if(id==='raiseNumber'&&$('raiseRange'))$('raiseRange').value=e.target.value;if(id==='masterVolume')audio.setMaster(Number(e.target.value)/100);if(id==='musicVolume')audio.setMusic(Number(e.target.value)/100);if(id==='ambienceVolume')audio.setAmbience(Number(e.target.value)/100);if(id==='reducedMotion'){$('stage').classList.toggle('gentle',e.target.checked);cat.tick(0,{gentle:e.target.checked,paused:paused(),hidden:document.hidden});}if(['masterVolume','musicVolume','ambienceVolume','reducedMotion'].indexOf(id)>=0)saveSettings();});
 function syncSettings(){$('masterVolume').value=audio.getMaster()*100;$('musicVolume').value=audio.getMusic()*100;$('ambienceVolume').value=audio.getAmbience()*100;$('muteButton').textContent=audio.isMuted()?'Unmute sounds':'Mute all';$('gamePace').value=pace;saveSession();}
 document.addEventListener('keydown',function(e){if(e.key==='Escape'){e.preventDefault();if(e.repeat)return;if(paused())closeAll();else{if(raiseOpen)renderActions();syncSettings();openModal('settings');}return;}if(e.key==='Tab'&&paused()){var modal=['journal','settings','rules','confirmReset','recap'].map($).find(function(x){return !x.classList.contains('hidden');});var focusable=Array.from(modal.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled)')).filter(function(el){return el.getClientRects().length>0;});if(focusable.length){var first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(e.target.tagName==='INPUT'||e.target.tagName==='SELECT')return;if(e.key.toLowerCase()==='h'){e.preventDefault();if(!$('journal').classList.contains('hidden'))closeAll();else openJournal();}if(paused()||e.repeat)return;if(e.key.toLowerCase()==='c'&&started&&table.actor===0&&!busy)act(table.legalActions().check?'check':'call');if(e.key.toLowerCase()==='f')act('fold');});
 var npcHoverTimes={},lastNpcSound=0;
 document.addEventListener('companion-hover',function(e){if(paused()||document.hidden)return;var now=performance.now(),key=e.detail.character,el=e.target;if(now-(npcHoverTimes[key]||-9999)<4000)return;npcHoverTimes[key]=now;el.classList.remove('hover-react');void el.offsetWidth;el.classList.add('hover-react');setTimeout(function(){el.classList.remove('hover-react');},1150);if(started&&now-lastNpcSound>750){audio.play('npc_'+key,{volume:.45,pan:Number(el.dataset.pan)});lastNpcSound=now;}});
 var lastHover=0;document.addEventListener('mouseover',function(e){if(!started||!e.target.closest('button')||Date.now()-lastHover<80)return;lastHover=Date.now();sound('hover');});
 function atmosphere(){var cv=$('atmosphere'),ctx=cv.getContext('2d'),motes=[];for(var i=0;i<24;i++)motes.push({x:Math.random()*1440,y:Math.random()*900,r:1+Math.random()*2,s:.1+Math.random()*.16,p:Math.random()*6});var frames=0;function frame(){requestAnimationFrame(frame);if(++frames%2||$('reducedMotion').checked||document.hidden)return;ctx.clearRect(0,0,1440,900);motes.forEach(function(m){m.y-=m.s;m.x+=Math.sin(frames*.002+m.p)*.13;if(m.y<0)m.y=900;ctx.fillStyle='rgba(242,203,134,'+(.10+.10*Math.sin(frames*.013+m.p))+')';ctx.fillRect(Math.floor(m.x/2)*2,Math.floor(m.y/2)*2,2,2);});}frame();}atmosphere();
 window.hearth={table:table,audio:audio,companions:companions,cat:cat,ambience:ambience,computation:computation,saveSession:saveSession,openJournal:openJournal,closeAll:closeAll,getState:function(){return {started:started,joining:joining,activeSeat:activeSeat,busy:busy,paused:paused(),visibleBoard:visibleBoard.map(function(c){return Object.assign({},c);}),revealed:revealed,visiblePot:visiblePot,visibleSeats:visibleSeats.map(function(p){return Object.assign({},p);}),companionSpeech:companions.getState()};}};
 var companionClock=Date.now();setInterval(function(){var now=Date.now();var context=companionContext();companions.tick(now-companionClock,context);cat.tick(now-companionClock,{hidden:context.hidden,paused:context.paused,gentle:$('reducedMotion').checked});ambience.setPaused(context.paused);companionClock=now;},80);document.addEventListener('visibilitychange',function(){companionClock=Date.now();companions.tick(0,companionContext());syncScenePause();});
 configureSeats();$('stage').style.setProperty('--pace',HearthSession.paceFactor(pace));syncSettings();companions.clear();render();setTimeout(function(){if(!started)companions.handle({type:'greeting'},companionContext());},600);
 addEventListener('pagehide',function(e){saveSession();if(!e.persisted)computation.dispose();});
 console.info('Hearthside ready · original art and sound · offline play');
})();

