(function(global){
 'use strict';var $=id=>document.getElementById(id),native=null,state=null,dirty=false,busy=false,timer;
 var mode=$('displayMode'),resolution=$('displayResolution'),quality=$('displayQuality'),fps=$('displayFPS'),apply=$('applyDisplay'),note=$('displayNote'),status=$('displayStatus');
 function parse(x){var s=typeof x==='string'?JSON.parse(x):x;if(!s||s.ok===false)throw Error(s&&s.error||'Display unavailable.');return s;}
 function fill(s,useMode){var target=useMode&&s.layouts&&s.layouts[mode.value],w=target?target.width:s.windowedWidth||s.width,h=target?target.height:s.windowedHeight||s.height,key=w+'x'+h,sizes=(s.resolutions||[]).slice();if(!sizes.some(x=>x.width+'x'+x.height===key))sizes.push({width:w,height:h});resolution.innerHTML='';sizes.forEach(x=>{var o=document.createElement('option');o.value=x.width+'x'+x.height;o.textContent=x.width+' × '+x.height;resolution.appendChild(o);});resolution.value=key;}
 function controls(){mode.disabled=busy;quality.disabled=busy||!native;fps.disabled=busy||!native;resolution.disabled=busy||!native||mode.value==='fullscreen';apply.disabled=busy||(!native&&!document.documentElement.requestFullscreen);mode.querySelector('[value="borderless"]').disabled=!native;note.textContent=!native?'Window controls are available in the standalone game.':mode.value==='fullscreen'?'Fills your monitor without changing its desktop resolution.':mode.value==='borderless'?'No title bar. Resize at the edges, or use Move / Resize at the top. Enter finishes; Escape cancels.':'A normal window with a title bar and resize borders.';}
 function accept(value,force){var s=parse(value);state=s;if(force||!dirty){mode.value=s.mode;fill(s,false);quality.value=String(s.scale);fps.value=String(s.frameRateLimit);}var output=s.outputWidth+' × '+s.outputHeight,render=s.renderWidth+' × '+s.renderHeight;$('displayActual').textContent='Current window: '+output+(s.maximized?' · maximized':'')+'\nRendered image: '+render+' · '+s.scale+'%';status.textContent=output+' · '+s.scale+'%';$('windowTools').classList.toggle('hidden',s.mode!=='borderless');controls();return s;}
 function fail(e){status.textContent=e.message||'Could not apply display settings.';}
 function refresh(){if(native&&!busy)return Promise.resolve(native.getsettings()).then(s=>accept(s,false)).catch(fail);if(!native){mode.value=document.fullscreenElement?'fullscreen':'windowed';controls();}return Promise.resolve(state);}
 async function applySettings(){if(busy)return;busy=true;controls();status.textContent='Applying…';try{if(native){var size=resolution.value.split('x'),requestedFPS=+fps.value;await native.setfps(requestedFPS);accept(await native.applysettings(mode.value,+size[0],+size[1],+quality.value),true);}else if(mode.value==='fullscreen')await document.documentElement.requestFullscreen();else if(document.fullscreenElement)await document.exitFullscreen();dirty=false;}catch(e){fail(e);}finally{busy=false;controls();setTimeout(refresh,500);}}
 async function toggleFullscreen(){if(busy)return;if(!native){mode.value=document.fullscreenElement?'windowed':'fullscreen';return applySettings();}busy=true;try{accept(await native.togglefullscreen(),true);dirty=false;}catch(e){fail(e);}finally{busy=false;controls();setTimeout(refresh,500);}}
 async function quit(){if(native){try{await native.windowaction('quit');}catch(e){$('saveStatus').textContent=e.message;}}else $('saveStatus').textContent='Your hand is saved. You can close this browser tab.';}
 function connect(n){var b=global.ue&&global.ue.hearthdisplay;if(b&&b.getsettings){native=b;refresh();}else if(n<50)setTimeout(()=>connect(n+1),100);else controls();}
 mode.addEventListener('change',()=>{dirty=true;if(state&&mode.value!=='fullscreen')fill(state,true);controls();});[resolution,quality,fps].forEach(e=>e.addEventListener('change',()=>{dirty=true;controls();}));apply.addEventListener('click',applySettings);
 var tabs=Array.from(document.querySelectorAll('[data-settings-tab]'));tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>{tabs.forEach(t=>{var selected=t===tab;t.classList.toggle('selected',selected);t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;});document.querySelectorAll('.settings-pane').forEach(p=>p.classList.toggle('hidden',p.id!==tab.dataset.settingsTab));if(tab.dataset.settingsTab==='displayPane')refresh();});tab.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();var next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length;tabs[next].click();tabs[next].focus();}});});
 document.querySelectorAll('[data-window]').forEach(b=>b.addEventListener('click',async()=>{if(native)try{await native.windowaction(b.dataset.window);}catch(e){fail(e);}}));
 document.addEventListener('keydown',e=>{if(e.key==='F11'||e.key==='Enter'&&e.altKey){e.preventDefault();if(!e.repeat)toggleFullscreen();}});document.addEventListener('fullscreenchange',refresh);global.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(refresh,300);});
 global.hearthDisplay={refresh:refresh,toggleFullscreen:toggleFullscreen,quit:quit,onNativeState:s=>accept(s,false)};controls();connect(0);
})(window);
