(function(g){'use strict';
var all=[
 {name:'Juniper',animal:'Fox',asset:'juniper',style:'Playful · small probing raises'},
 {name:'Luna',animal:'Moth',asset:'luma',style:'Observant · cautious and selective'},
 {name:'Moss',animal:'Frog',asset:'moss',style:'Unhurried · modest calls'},
 {name:'Clipper',animal:'Crocodile',asset:'clipper',style:'Patient · waits for value, bets firmly'},
 {name:'Mur',animal:'Axolotl',asset:'mur',style:'Curious · explores affordable draws'},
 {name:'Baron',animal:'Dog',asset:'baron',style:'Steady · calls loyally, raises sparingly'}
];
var $=id=>document.getElementById(id);
function selected(){return Array.from(document.querySelectorAll('#rosterChoices input:checked')).map(e=>e.value);}
function update(){var n=Number($('tableSize').value)-1,count=selected().length;$('rosterStatus').textContent='Choose '+n+' companions · '+count+' selected';$('resetConfirm').disabled=count!==n;document.querySelectorAll('#rosterChoices input').forEach(e=>{e.disabled=!e.checked&&count>=n;});}
function setup(names){$('tableSize').value=String(names.length+1);$('rosterChoices').innerHTML='';all.forEach(c=>{var label=document.createElement('label');label.className='roster-choice';var input=document.createElement('input');input.type='checkbox';input.value=c.name;input.checked=names.includes(c.name);label.appendChild(input);var text=document.createElement('span');text.textContent=c.name+' · '+c.animal;var sub=document.createElement('small');sub.textContent=c.style;text.appendChild(sub);label.appendChild(text);$('rosterChoices').appendChild(label);});update();}
function mount(players,variant){document.querySelectorAll('.companion').forEach(e=>e.remove());$('stage').classList.remove('six-seats');$('stage').dataset.players=players.length;var layout=HearthSeating.layout(players.length,variant);players.slice(1).forEach((p,i)=>{var c=all.find(c=>c.asset===p.avatar)||all.find(c=>c.name===p.name)||all[i%all.length],el=document.createElement('div');el.className='companion seated-companion';var slot=layout[p.id];el.style.left=slot.body.x+'px';el.style.top=slot.body.y+'px';el.dataset.pan=slot.pan;el.dataset.near=slot.near;el.dataset.chipX=slot.chips.x+32;el.dataset.chipY=slot.chips.y+13;el.style.setProperty('--facing',slot.mirror?-1:1);['label','cards','chips'].forEach(function(k){el.style.setProperty('--'+k+'-x',(slot[k].x-slot.body.x)+'px');el.style.setProperty('--'+k+'-y',(slot[k].y-slot.body.y)+'px');});el.id='seat'+p.id;el.dataset.slot=i+1;el.dataset.character=c.asset;el.innerHTML='<div class="speech" id="speech'+p.id+'" aria-live="polite"></div><div class="sprite-facing"><div class="sprite"></div></div><div class="nameplate"><span class="dealer-token">D</span><strong></strong><span class="persona"></span><div class="bank"><span class="chip-symbol">◉</span> <b class="stack">500</b><span class="status">Ready</span></div></div><div class="opponent-cards"></div><div class="npc-chips" role="img"></div>';el.querySelector('strong').textContent=(p.name||c.name).toUpperCase();el.querySelector('.nameplate').title=c.animal+' · '+c.style;el.querySelector('.sprite').style.backgroundImage='url("assets/'+c.asset+(['luma','clipper'].includes(c.asset)?'-seated-v4.png':'-seated-v3.png')+'")';el.tabIndex=0;el.setAttribute('aria-label',c.name+', '+c.animal+'. '+c.style);function react(){el.dispatchEvent(new CustomEvent('companion-hover',{bubbles:true,detail:{id:p.id,character:c.asset}}));}el.addEventListener('pointerenter',react);el.addEventListener('focus',react);$('stage').appendChild(el);});}
$('rosterChoices').addEventListener('change',update);$('tableSize').addEventListener('change',()=>{var chosen=selected(),n=Number($('tableSize').value)-1;all.forEach(c=>{if(chosen.length<n&&!chosen.includes(c.name))chosen.push(c.name);});chosen=chosen.slice(0,n);document.querySelectorAll('#rosterChoices input').forEach(e=>e.checked=chosen.includes(e.value));update();});
g.HearthRoster={all,selected,setup,mount};
})(window);

