(function(){'use strict';
 var $=id=>document.getElementById(id),saved=null;try{saved=JSON.parse(localStorage.getItem('hearthside-lore'));}catch(e){}
 var story=new HearthLore.Story(saved),bridge=null,active=null,lastQuestionHand=-1;
 var stage=$('stage'),wrap=document.createElement('div');wrap.innerHTML='<div id="storyDialog" class="small-modal hidden" role="dialog" aria-modal="true" aria-labelledby="storyTitle"><button class="close" data-close="storyDialog" aria-label="Close conversation">×</button><span class="eyebrow">AT HEARTHSIDE</span><h2 id="storyTitle"></h2><div id="storyBody" aria-live="polite"></div><div id="storyActions"></div></div><div id="storyNotebook" class="small-modal hidden" role="dialog" aria-modal="true" aria-labelledby="notebookTitle"><button class="close" data-close="storyNotebook" aria-label="Close notebook">×</button><span class="eyebrow">YOUR OBSERVATIONS</span><h2 id="notebookTitle">Notebook</h2><div id="notebookPages"></div></div><button id="spareCupClue" class="lore-hotspot cup-clue" title="Inspect the spare cup between hands" aria-label="Inspect the spare cup"><span>Spare cup</span></button><button id="drawerClue" class="lore-hotspot drawer-clue" title="Inspect Moss’s drawer between hands" aria-label="Inspect Moss’s drawer"><span>Drawer</span></button>';
 while(wrap.firstChild)stage.appendChild(wrap.firstChild);
 var notebook=document.createElement('button');notebook.id='notebookButton';notebook.textContent='Notebook';document.querySelector('footer').appendChild(notebook);
 var settings=document.createElement('label');settings.className='display-field';settings.innerHTML='Story scenes<select id="storyMode"><option value="normal">Normal</option><option value="reduced">Occasional</option><option value="off">Off</option></select>';$('soundPane').appendChild(settings);$('storyMode').value=story.state.mode;
 var note=document.createElement('p');note.className='pace-note';note.textContent='Explore objects and click guests between hands. Notebook progress survives fresh tables.';$('soundPane').appendChild(note);
 var settingsNotebook=document.createElement('button');settingsNotebook.textContent='Open notebook';settingsNotebook.className='notebook-settings-link';settingsNotebook.addEventListener('click',openNotebook);$('soundPane').appendChild(settingsNotebook);
 function save(){try{localStorage.setItem('hearthside-lore',JSON.stringify(story.state));}catch(e){$('loreSaveNote')?.remove();var p=document.createElement('p');p.id='loreSaveNote';p.textContent='Notebook could not be saved on this device.';$('storyBody').appendChild(p);}}
 function context(){return bridge?bridge.context():{guests:[],between:false};}
 function button(text,fn){var b=document.createElement('button');b.textContent=text;b.addEventListener('click',fn);$('storyActions').appendChild(b);return b;}
 function text(tag,value,parent){var e=document.createElement(tag);e.textContent=value;parent.appendChild(e);return e;}
 function panel(title){bridge.open('storyDialog');$('storyTitle').textContent=title;$('storyBody').replaceChildren();$('storyActions').replaceChildren();}
 function reactions(scene,speaker){document.querySelectorAll('.companion').forEach(el=>{el.classList.remove('lore-still','lore-watch','lore-falter','lore-lean','lore-envelope','lore-away');var name=HearthRoster.all.find(c=>c.asset===el.dataset.character)?.name;if(scene){var effect=scene.reactions&&scene.reactions[name];if(effect)el.classList.add('lore-'+effect);if(scene.private&&!scene.guests.includes(name))el.classList.add('lore-away');}});}
 function dialogue(scene,done){panel(scene.title||scene.prompt);active={scene:scene,index:0,done:done};showLine();}
 function showLine(){var a=active,line=a.scene.lines[a.index];$('storyBody').replaceChildren();text('strong',line[0],$('storyBody'));text('p',line[1],$('storyBody'));$('storyActions').replaceChildren();reactions(a.scene,line[0]);button(a.index===a.scene.lines.length-1?'Continue':'Next',()=>{if(++a.index<a.scene.lines.length){showLine();return;}story.finish(a.scene);save();active=null;reactions(null);bridge.close();if(a.done)a.done();}).className='primary';button('Later',()=>{var done=a.done;story.defer();save();active=null;reactions(null);bridge.close();if(done)done();});document.querySelector('#storyActions button').focus();}
 function inspect(id){var c=context();if(!c.between||story.state.mode==='off')return;var found=story.observe(id,c.guests);if(!found)return;save();panel(found.object.title);text('p',found.text,$('storyBody'));if(found.object.owner)askButton(found.object.owner);button('Back to the table',()=>bridge.close());}
 function askButton(name){var q=story.question(name);if(q&&lastQuestionHand!==story.state.hands)button(q.prompt,()=>{lastQuestionHand=story.state.hands;dialogue(q);});}
 function guest(name){var c=context();if(!c.between||story.state.mode==='off')return;panel(name);var o=HearthLore.objects.find(o=>o.owner===name&&o.id!=='drawer');if(!o)o=HearthLore.objects.find(o=>o.owner===name);text('p',{Juniper:'Juniper rolls a chip across her knuckles.',Luna:'Luna keeps a finger between the pages.',Moss:'Moss checks whether anyone needs more tea.',Clipper:'Clipper settles his glasses on his snout.',Mur:'Mur is tracing shapes in a patch of spilled tea.',Baron:'Baron shifts his chair to give you room.'}[name],$('storyBody'));if(o)button('Look closer: '+o.title,()=>inspect(o.id));askButton(name);button('Leave them to it',()=>bridge.close());}
 function openNotebook(){if(!bridge)return;bridge.open('storyNotebook');var pages=$('notebookPages');pages.replaceChildren();var s=story.state;if(!s.observed.length&&!s.scenes.length){text('p','Nothing written yet. Between hands, look at the spare cup or click a guest. There is no need to win to get to know them.',pages);return;}
  text('h3','Objects & memories',pages);HearthLore.objects.filter(o=>s.observed.includes(o.id)).forEach(o=>{var entry=document.createElement('details');text('summary',o.title,entry);var paths={cup:'M8 12h20v12q-10 10-20 0z M28 14h5q7 9-5 9 M5 33h30',drawer:'M5 9h30v24H5z M5 20h30 M17 15h6 M17 26h6',book:'M20 10Q10 4 4 9v25q10-5 16 0q9-5 16 0V9q-8-5-16 1v24',watch:'M17 4h6v5h-6z M20 12a12 12 0 1 0 0 24a12 12 0 1 0 0-24 M20 16v9l6 3',letter:'M4 11h32v23H4z M4 11l16 12 16-12',coat:'M4 11h32v23H4z M4 11l16 12 16-12 M16 29h8',memory:'M5 34V12L20 3l15 9v22z M12 17h9v9h-9z M26 34V23h6'};var sketch=document.createElementNS('http://www.w3.org/2000/svg','svg');sketch.setAttribute('viewBox','0 0 40 40');sketch.setAttribute('class','notebook-sketch');sketch.setAttribute('aria-hidden','true');var path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',paths[o.id]);sketch.appendChild(path);entry.appendChild(sketch);text('p',o.text,entry);pages.appendChild(entry);});
  var known=HearthLore.questions.filter(q=>s.questions.includes(q.id)).concat(HearthLore.scenes.filter(q=>s.scenes.includes(q.id)));if(known.length){text('h3','Conversations',pages);known.forEach(q=>{var entry=document.createElement('details');text('summary',q.title||q.prompt,entry);text('p',q.note,entry);q.lines.forEach(line=>text('p',line[0]+': “'+line[1]+'”',entry));pages.appendChild(entry);});}
  text('h3','Open questions',pages);var list=document.createElement('ul');HearthLore.objects.filter(o=>s.observed.includes(o.id)).concat(known).filter(o=>o.question).forEach(o=>text('li',o.question,list));pages.appendChild(list);
 }
 function availability(){var c=context(),enabled=c.between&&story.state.mode!=='off';stage.classList.toggle('lore-available',enabled);$('spareCupClue').disabled=!enabled;$('drawerClue').disabled=!enabled||!c.guests.includes('Moss');document.querySelectorAll('.companion').forEach(el=>{el.title=enabled?'Click to spend a moment with this guest':'';});}
 $('notebookButton').addEventListener('click',openNotebook);$('spareCupClue').addEventListener('click',()=>inspect('cup'));$('drawerClue').addEventListener('click',()=>inspect('drawer'));
 $('storyMode').addEventListener('change',function(){story.state.mode=this.value;save();availability();});
 document.addEventListener('click',e=>{var el=e.target.closest('.companion');if(el&&!e.target.closest('button')&&bridge&&!context().paused){var c=HearthRoster.all.find(c=>c.asset===el.dataset.character);if(c)guest(c.name);}});
 document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.companion')&&!context().paused){e.preventDefault();var c=HearthRoster.all.find(c=>c.asset===e.target.dataset.character);if(c)guest(c.name);}});
 window.HearthStory={connect:function(b){bridge=b;availability();},refresh:availability,completeHand:function(token,names){story.completeHand(token,names);save();availability();},cancel:function(){if(active){story.defer();save();active=null;}reactions(null);},beforeDeal:function(done){var c=context(),scene=story.next(c.guests);if(!scene){done();return;}if(scene.private){panel('Stay a moment?');text('p','Clipper and Baron are still talking quietly. You can stay, or deal the next hand.',$('storyBody'));button('Stay a moment',()=>dialogue(scene,done));button('Deal next hand',()=>{story.defer();save();bridge.close();done();});}else dialogue(scene,done);},openNotebook:openNotebook};
})();

