/* Opening chapter. This module receives names and completed-hand tokens, never cards or betting state. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HearthLore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 'use strict';
 var objects=[
  {id:'cup',title:'The spare cup',owner:null,text:'A clean cup sits apart from the others. Its handle has been repaired with a narrow seam of brass.',repeat:'The spare cup is still clean. Someone has turned its repaired handle towards the room.',question:'Who is the spare cup for?'},
  {id:'drawer',title:'Moss’s drawer',owner:'Moss',text:'Moss opens the drawer just far enough to find a spoon. Inside are small paper parcels, each with a handwritten number. Something knocks against the wood like loose buttons.',repeat:'Moss offers you a clean spoon. The parcels remain carefully wrapped.',question:'Why wrap ordinary buttons separately?'},
  {id:'book',title:'Luna’s book',owner:'Luna',text:'The book is labelled Local Walks. A folded diagram inside shows channels, gate numbers and a settlement called Reedbank. Luna closes it with one finger keeping her place.',repeat:'Luna is reading the appendix again. The walking routes have no annotations.',question:'Why is there a reservoir diagram in a walking book?'},
  {id:'watch',title:'Clipper’s watch',owner:'Clipper',text:'Clipper checks a small watch before returning it to his pocket. You hear no ticking. Its hands read 2:17.',repeat:'The hands still read 2:17. Clipper winds nothing before putting it away.',question:'Why carry a watch that has stopped?'},
  {id:'letter',title:'Juniper’s envelope',owner:'Juniper',text:'Juniper catches an envelope slipping from her waistcoat. The address is written in exceptionally neat, square lettering. You glimpse a name beginning with E before she turns it over.',repeat:'Juniper’s envelope has been folded and unfolded until its edges are soft.',question:'Who was Juniper before she was Juniper?'},
  {id:'coat',title:'Baron’s coat',owner:'Baron',text:'A heavy envelope has worn a pale rectangle into the inside of Baron’s coat. It is still sealed. Someone once wrote URGENT across the front.',repeat:'Baron checks the inner pocket before hanging his coat up again.',question:'Why has an urgent delivery never been opened?'},
  {id:'memory',title:'Mur’s kitchen',owner:'Mur',text:'Mur traces a rectangle in a patch of spilled tea. “Our kitchen was blue. I think. The ceiling used to shine.” They smile, trying to remember the colour properly.',repeat:'Mur remembers the kitchen’s colour more clearly than the house around it.',question:'Where was the house with the blue kitchen?'}
 ];
 var questions=[
  {id:'ask_moss',owner:'Moss',needs:['cup'],prompt:'Who is the spare cup for?',lines:[['Moss','Someone who liked the handle that way round.'],['You','Are they coming back?'],['Moss','It takes very little work to wash one more cup.']],note:'Moss answered a question about the cup’s owner by talking about keeping it ready.'},
  {id:'ask_luna',owner:'Luna',needs:['book'],prompt:'You marked Reedbank on that map.',lines:[['Luna','It isn’t on the newer editions.'],['You','Was it too small?'],['Luna','Small places still take up space.']],note:'Luna is comparing editions of a map. Reedbank disappears from the newer ones.'},
  {id:'ask_clipper',owner:'Clipper',needs:['watch'],prompt:'Your watch has stopped.',lines:[['Clipper','Yes.'],['You','Would you like someone to repair it?'],['Clipper','It tells me what I need to know. Thank you.']],note:'Clipper knows the watch is stopped. He declined to have it repaired.'},
  {id:'ask_juniper',owner:'Juniper',needs:['letter'],prompt:'That is very careful handwriting.',lines:[['Juniper','A useful skill in an unreliable profession.'],['You','Storytelling?'],['Juniper','Among others.']],note:'Juniper called her handwriting a professional skill, but did not name the profession.'},
  {id:'ask_mur',owner:'Mur',needs:['memory'],prompt:'What else do you remember about the kitchen?',lines:[['Mur','A window that stuck. A red tin. Someone singing about stairs.'],['You','Do you remember the song?'],['Mur','Only the counting part. It ends before I expect it to.']],note:'Mur remembers a red tin, a sticking window and a song about counting stairs.'},
  {id:'ask_baron',owner:'Baron',needs:['coat'],prompt:'Did that delivery ever arrive?',lines:[['Baron','I still have it.'],['You','I meant—'],['Baron','I know. I’m sorry.']],note:'Baron still carries the sealed delivery. He did not say where it was meant to go.'}
 ];
 var scenes=[
  {id:'extra_cup',guests:['Moss'],after:2,needs:[],grants:['cup'],title:'One more cup',lines:[['Moss','Careful of the handle on that one.'],['You','Shall I put it away?'],['Moss','Leave it there, if you don’t mind.']],note:'Moss keeps a repaired cup out even when nobody uses it.'},
  {id:'blue_kitchen',guests:['Mur','Moss'],after:4,needs:['memory'],title:'A remembered room',lines:[['Mur','We had a blue kitchen like that.'],['Moss','Lots of houses did.'],['Mur','You didn’t ask where.'],['Moss','No. I didn’t.']],note:'Moss answered Mur’s memory before asking where the house was.',question:'Did Moss know Mur’s childhood home?',reactions:{Moss:'still',Mur:'lean'}},
  {id:'stopped_time',guests:['Luna','Clipper'],after:5,needs:['watch','book'],title:'The margin of a page',lines:[['Luna','Two seventeen. That appears in the maintenance log as well.'],['Clipper','There were several clocks.'],['Luna','I haven’t told you which log.'],['Clipper','Then I should not have assumed.']],note:'Clipper connected 2:17 to a log before Luna identified it.',question:'Which event does the stopped watch mark?',reactions:{Clipper:'watch',Luna:'still'}},
  {id:'the_word',guests:['Juniper','Luna'],after:6,needs:['letter','book'],title:'A correction',lines:[['Luna','It says the settlement was vacant.'],['Juniper','Unoccupied.'],['Luna','Does that mean something different?'],['Juniper','To whoever wrote it, apparently.']],note:'Juniper corrected the wording of a record Luna was reading without looking at the page.',question:'Has Juniper seen the occupancy record before?',reactions:{Juniper:'falter'}},
  {id:'counting',guests:['Mur','Moss','Baron'],after:8,needs:['memory','coat'],title:'The unfinished tune',lines:[['Mur','One for the landing, two for the door…'],['Baron','Three. There were three steps after the turn.'],['Mur','That isn’t how the song goes.'],['Baron','No. Sorry. A different staircase.']],note:'Baron supplied a detail about stairs when Mur began their childhood song. Moss stopped stirring.',question:'Were Baron and Mur remembering the same place?',reactions:{Moss:'still',Baron:'envelope'}},
  {id:'parcel',guests:['Mur','Moss'],after:10,needs:['drawer','memory'],sceneNeeds:['blue_kitchen'],title:'A small blue button',lines:[['Mur','My mother had buttons like that.'],['Moss','Quite a few people did.'],['Mur','One was chipped on the back. May I see?'],['Moss','Yes. But carefully.']],note:'Mur recognised a button from one of Moss’s numbered parcels. Moss let them examine it.',question:'What do the parcel numbers record?',reactions:{Moss:'still',Mur:'lean'}},
  {id:'little_time',guests:['Clipper','Baron'],after:12,needs:['watch','coat'],sceneNeeds:['stopped_time'],title:'After the others quieten',private:true,lines:[['Clipper','There was very little time.'],['Baron','There was time to stop.'],['Clipper','For you.'],['Baron','Yes. For me.']],note:'Clipper and Baron remember the same night differently. Neither named it.',question:'What did Baron stop to do?',reactions:{Clipper:'still',Baron:'envelope'}}
 ];
 function fresh(){return {version:1,mode:'normal',hands:0,lastScene:-2,observed:[],questions:[],scenes:[],tokens:[],familiarity:{}};}
 function Story(saved){this.state=fresh();if(saved&&saved.version===1){var s=this.state;s.mode=['normal','reduced','off'].includes(saved.mode)?saved.mode:'normal';s.hands=Number.isSafeInteger(saved.hands)&&saved.hands>=0?saved.hands:0;s.lastScene=Number.isSafeInteger(saved.lastScene)?Math.min(saved.lastScene,s.hands):-2;for(var pair of [['observed',objects],['questions',questions],['scenes',scenes]])s[pair[0]]=Array.isArray(saved[pair[0]])?saved[pair[0]].filter(id=>pair[1].some(x=>x.id===id)):[];s.tokens=Array.isArray(saved.tokens)?saved.tokens.filter(x=>typeof x==='string').slice(-64):[];s.familiarity=saved.familiarity&&typeof saved.familiarity==='object'?saved.familiarity:{};}}
 Story.prototype.completeHand=function(token,guests){var s=this.state;if(s.tokens.includes(token))return false;s.tokens.push(token);s.tokens=s.tokens.slice(-64);if(s.mode==='off')return false;s.hands++;guests.forEach(n=>s.familiarity[n]=(Number(s.familiarity[n])||0)+1);return true;};
 Story.prototype.observe=function(id,guests){var o=objects.find(x=>x.id===id);if(!o||this.state.mode==='off'||o.owner&&!guests.includes(o.owner))return null;var first=!this.state.observed.includes(id);if(first)this.state.observed.push(id);return {object:o,text:first?o.text:o.repeat};};
 Story.prototype.question=function(owner){return questions.find(q=>q.owner===owner&&!this.state.questions.includes(q.id)&&q.needs.every(n=>this.state.observed.includes(n)));};
 Story.prototype.next=function(guests){var s=this.state;if(s.mode==='off'||s.hands-s.lastScene<(s.mode==='reduced'?4:2))return null;return scenes.find(x=>!s.scenes.includes(x.id)&&s.hands>=x.after&&x.guests.every(n=>guests.includes(n))&&x.needs.every(n=>s.observed.includes(n))&&(!x.sceneNeeds||x.sceneNeeds.every(n=>s.scenes.includes(n))))||null;};
 Story.prototype.finish=function(scene){var s=this.state;if(questions.some(q=>q.id===scene.id)){if(!s.questions.includes(scene.id))s.questions.push(scene.id);}else if(scenes.some(q=>q.id===scene.id)){if(!s.scenes.includes(scene.id))s.scenes.push(scene.id);s.lastScene=s.hands;(scene.grants||[]).forEach(id=>{if(!s.observed.includes(id))s.observed.push(id);});}};
 Story.prototype.defer=function(){this.state.lastScene=this.state.hands;};
 return {Story:Story,objects:objects,questions:questions,scenes:scenes};
});

