const test=require('node:test'),assert=require('node:assert/strict'),Poker=require('../poker.js'),S=require('../session.js');
function ui(t){return {eventIndex:t.events.length,visibleBoard:t.board,visibleSeats:t.players.map(p=>({stack:p.stack,bet:p.bet,folded:p.folded,allIn:p.allIn,lastAction:p.lastAction})),visiblePot:t.pot,visibleStreet:t.street,revealed:!!t.result,message:'Saved'};}
function step(t){let l=t.legalActions();t.act(t.actor,l.check?'check':'call');}
test('unfinished hand roundtrips deck, private cards, legal turn and chip contributions',()=>{let t=new Poker.Table();t.newHand();step(t);let restored=S.unpack(S.pack(t,ui(t))).table;assert.deepEqual(restored.snapshot({revealAll:true}),t.snapshot({revealAll:true}));assert.deepEqual(restored.deck,t.deck);assert.deepEqual(restored.legalActions(),t.legalActions());while(!t.result){step(t);step(restored);}assert.deepEqual(restored.result,t.result);});
test('every betting street and completed hand can be reopened without re-awarding chips',()=>{let t=new Poker.Table();t.newHand();let seen=new Set();while(true){let r=S.unpack(S.pack(t,ui(t))).table;assert.equal(r.players.reduce((s,p)=>s+p.stack+p.totalBet,0),2000);seen.add(t.street);if(t.result){assert.deepEqual(r.result,t.result);break;}step(t);}assert.deepEqual([...seen],['preflop','flop','turn','river','showdown']);});
test('save isolates live references and preserves pending presentation events',()=>{let t=new Poker.Table();t.newHand();let u=ui(t);u.eventIndex=0;u.visibleBoard=[];let s=S.pack(t,u);t.deck.pop();u.visibleSeats[0].stack=0;let restored=S.unpack(s);assert.equal(restored.ui.eventIndex,0);assert.equal(restored.table.events[0].type,'hand-start');assert.equal(restored.ui.visibleSeats[0].stack,500);});
test('corrupt card, money and actor saves are rejected',()=>{let t=new Poker.Table();t.newHand();for(const change of [s=>s.table.deck.push(s.table.deck[0]),s=>s.table.players[0].stack++,s=>s.table.actor=8,s=>s.ui.visibleBoard=[{rank:14,suit:'x'}]]){let s=S.pack(t,ui(t));change(s);assert.throws(()=>S.unpack(s));}});
test('same pair kicker, ties and distinct categories explain the deciding hand',()=>{let a=Poker.evaluate([{rank:12,suit:'s'},{rank:12,suit:'h'},{rank:14,suit:'d'},{rank:8,suit:'c'},{rank:4,suit:'s'}]);let b=Poker.evaluate([{rank:12,suit:'d'},{rank:12,suit:'c'},{rank:13,suit:'d'},{rank:8,suit:'h'},{rank:4,suit:'h'}]);assert.match(S.explain(a,b),/Ace kicker beats the King kicker/);assert.match(S.explain(a,a),/tie/);assert.match(S.explain(a,{category:0,name:'High Card',tiebreak:[14]}),/One Pair beats High Card/);});
test('fold recap never reveals unshown cards, showdown highlights five cards',()=>{let t=new Poker.Table();t.newHand();while(!t.result)t.act(t.actor,'fold');let r=S.recap(t.result,['You','Juniper','Luma','Moss']);assert.equal(r[0].winners[0].cards.length,0);let q=new Poker.Table();q.newHand();while(!q.result)step(q);for(let pot of S.recap(q.result,['You','Juniper','Luma','Moss']))for(let w of pot.winners)assert.equal(w.cards.length,5);});
test('pace choices alter presentation duration without changing poker actions',()=>{assert.ok(S.paceFactor('relaxed')>1);assert.equal(S.paceFactor('normal'),1);assert.ok(S.paceFactor('brisk')<1);assert.equal(S.paceFactor('unknown'),1);});
test('a partially displayed flop preserves its cursor and only the remaining cards replay',()=>{let t=new Poker.Table();t.newHand();while(t.street==='preflop')step(t);let u=ui(t),e=t.events.find(e=>e.type==='street');u.eventIndex=t.events.indexOf(e);u.visibleBoard=t.board.slice(0,1);let r=S.unpack(S.pack(t,u));let shown=r.ui.visibleBoard;let start=shown.length-(e.board.length-e.cards.length);shown.push(...e.cards.slice(start));assert.deepEqual(shown,t.board);assert.equal(new Set(shown.map(Poker.cardKey)).size,3);});
test('short all-in reopening restrictions survive a saved hand',()=>{let t=new Poker.Table();t.players[1].stack=35;t.players[2].stack=965;t.newHand();t.act(3,'raise',30);t.act(0,'call');t.act(1,'allin');t.act(2,'call');let r=S.unpack(S.pack(t,ui(t))).table;assert.equal(r.actor,3);assert.equal(r.legalActions().canRaise,false);assert.equal(r.legalActions().call,5);assert.throws(()=>r.act(3,'raise',55));while(!t.result){step(t);step(r);}assert.deepEqual(r.result,t.result);});
test('split-pot recap assigns the odd chip in the engine winner order',()=>{let hand=Poker.evaluate([{rank:14,suit:'s'},{rank:13,suit:'s'},{rank:12,suit:'s'},{rank:11,suit:'s'},{rank:10,suit:'s'}]);let r=S.recap({reason:'showdown',pots:[{amount:5,eligible:[1,2],winners:[2,1],uncalled:false}],showdown:[{id:1,hand},{id:2,hand}]},['You','Juniper','Luma','Moss']);assert.deepEqual(r[0].winners.map(w=>[w.name,w.amount]),[['Luma',3],['Juniper',2]]);assert.match(r[0].text,/odd chip/);});
